<a href="https://colab.research.google.com/github/bvinaykumarmtech/Machine-Learning/blob/main/Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
# Creation of 1-D Arrays
import numpy as np
n1 = np.array([10, 20, 30, 40, 50])
print(n1)
print(type(n1))
n1

[10 20 30 40 50]
<class 'numpy.ndarray'>


array([10, 20, 30, 40, 50])

In [7]:
# Creation of 2-D Arrays
import numpy as np
n2 = np.array([[10, 20, 30, 40, 50],[50, 40, 30, 20, 10]])
print(n2)
print(type(n2))
n2

[[10 20 30 40 50]
 [50 40 30 20 10]]
<class 'numpy.ndarray'>


array([[10, 20, 30, 40, 50],
       [50, 40, 30, 20, 10]])

In [10]:
# Initializing NumPy array with zeros
import numpy as np
n1 = np.zeros((1,2))
n1

array([[0., 0.]])

In [11]:
# Initializing NumPy array with zeros
import numpy as np
n1 = np.zeros((5,5))
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
# Initializing NumPy array with same number
# It will take 2 parameters First is dimensions Second is value to be filled
import numpy as np
n1 = np.full((3, 3),(5))
n1

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [15]:
# Initializing NumPy array within a range
# It will take 2 parameters First is starting Second is value is stop-1
import numpy as np
n1 = np.arange(10, 20)
n1

array([10, 13, 16, 19, 22, 25, 28])

In [17]:
# Initializing NumPy array within a range
# It will take 3 parameters First is starting Second is value is stop-1 third is step
import numpy as np
n1 = np.arange(10, 30, 2)
n1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [20]:
# Initializing NumPy array with random numbers
# It will take 3 parameters First is starting Second is value is stop third is 5 random numbers
import numpy as np
n1 = np.random.randint(1, 100, 5)
n1

array([59, 80, 89, 89, 80])

In [21]:
# Checking the shape of NumPy arrays
import numpy as np
n1 = np.array([[1, 2, 3],[4, 5, 6]])
n1.shape

(2, 3)

In [24]:
# Checking the shape of NumPy arrays
import numpy as np
n1 = np.array([[1, 2, 3],[4, 5, 6]])
n1.shape = (3,2)
n1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
# vstack()
import numpy as np
n1=np.array([10, 20, 30])
n2=np.array([40, 50, 60])
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [26]:
# hstack()
import numpy as np
n1=np.array([10, 20, 30])
n2=np.array([40, 50, 60])
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [27]:
# column_stack()
import numpy as np
n1=np.array([10, 20, 30])
n2=np.array([40, 50, 60])
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [28]:
# NumPy Intersection & Difference
import numpy as np
n1 = np.array([10, 20, 30, 40, 50, 60])
n2 = np.array([50, 60, 70, 80, 90])
np.intersect1d(n1,n2)

array([50, 60])

In [29]:
# NumPy Intersection & Difference
import numpy as np
n1 = np.array([10, 20, 30, 40, 50, 60])
n2 = np.array([50, 60, 70, 80, 90])
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [30]:
# NumPy Intersection & Difference
import numpy as np
n1 = np.array([10, 20, 30, 40, 50, 60])
n2 = np.array([50, 60, 70, 80, 90])
np.setdiff1d(n2,n1)

array([70, 80, 90])

In [33]:
# NumPy Array Mathematics
# Addition of NumPy Arrays
import numpy as np
n1=np.array([10, 20])
n2=np.array([30, 40])
np.sum([n1, n2])

100

In [34]:
# NumPy Array Mathematics
# Addition of NumPy Arrays
import numpy as np
n1=np.array([10, 20])
n2=np.array([30, 40])
np.sum([n1, n2], axis=0)

array([40, 60])

In [35]:
# NumPy Array Mathematics
# Addition of NumPy Arrays
import numpy as np
n1=np.array([10, 20])
n2=np.array([30, 40])
np.sum([n1, n2], axis=1)

array([30, 70])

In [36]:
# NumPy Array Mathematics
# Basic Addition
import numpy as np
n1=np.array([10, 20, 30])
n1=n1+1
n1

array([11, 21, 31])

In [37]:
# NumPy Array Mathematics
# Basic Multiplication
import numpy as np
n1=np.array([10, 20, 30])
n1=n1*2
n1

array([20, 40, 60])

In [38]:
# NumPy Array Mathematics
# Basic Subtraction
import numpy as np
n1=np.array([10, 20, 30])
n1=n1-1
n1

array([ 9, 19, 29])

In [39]:
# NumPy Array Mathematics
# Basic Division
import numpy as np
n1=np.array([10, 20, 30])
n1=n1/2
n1

array([ 5., 10., 15.])

In [40]:
# NumPy Math Functions
# Mean
import numpy as np
n1=np.array([10, 20, 30, 40, 50, 60])
np.mean(n1)

35.0

In [44]:
# NumPy Math Functions
# Median
import numpy as np
n1=np.array([11, 44, 5, 96, 67, 85])
np.median(n1)

55.5

In [45]:
# NumPy Math Functions
# Standard Deviation
import numpy as np
n1=np.array([1, 5, 3, 100, 4, 48])
np.std(n1)

36.59424666377065