<a href="https://colab.research.google.com/github/bvinaykumarmtech/Machine-Learning/blob/main/Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Creation of 1-D Arrays
import numpy as np
n1 = np.array([10, 20, 30, 40, 50])
print(n1)
print(type(n1))
n1

[10 20 30 40 50]
<class 'numpy.ndarray'>


array([10, 20, 30, 40, 50])

In [ ]:
# Creation of 2-D Arrays
import numpy as np
n2 = np.array([[10, 20, 30, 40, 50],[50, 40, 30, 20, 10]])
print(n2)
print(type(n2))
n2

[[10 20 30 40 50]
 [50 40 30 20 10]]
<class 'numpy.ndarray'>


array([[10, 20, 30, 40, 50],
       [50, 40, 30, 20, 10]])

In [ ]:
# Initializing NumPy array with zeros
import numpy as np
n1 = np.zeros((1,2))
n1

array([[0., 0.]])

In [ ]:
# Initializing NumPy array with zeros
import numpy as np
n1 = np.zeros((5,5))
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# Initializing NumPy array with same number
# It will take 2 parameters First is dimensions Second is value to be filled
import numpy as np
n1 = np.full((3, 3),(5))
n1

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
# Initializing NumPy array within a range
# It will take 2 parameters First is starting Second is value is stop-1
import numpy as np
n1 = np.arange(10, 20)
n1

array([10, 13, 16, 19, 22, 25, 28])

In [ ]:
# Initializing NumPy array within a range
# It will take 3 parameters First is starting Second is value is stop-1 third is step
import numpy as np
n1 = np.arange(10, 30, 2)
n1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
# Initializing NumPy array with random numbers
# It will take 3 parameters First is starting Second is value is stop third is 5 random numbers
import numpy as np
n1 = np.random.randint(1, 100, 5)
n1

array([59, 80, 89, 89, 80])

In [ ]:
# Checking the shape of NumPy arrays
import numpy as np
n1 = np.array([[1, 2, 3],[4, 5, 6]])
n1.shape

(2, 3)

In [ ]:
# Checking the shape of NumPy arrays
import numpy as np
n1 = np.array([[1, 2, 3],[4, 5, 6]])
n1.shape = (3,2)
n1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# vstack()
import numpy as np
n1=np.array([10, 20, 30])
n2=np.array([40, 50, 60])
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
# hstack()
import numpy as np
n1=np.array([10, 20, 30])
n2=np.array([40, 50, 60])
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [ ]:
# column_stack()
import numpy as np
n1=np.array([10, 20, 30])
n2=np.array([40, 50, 60])
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [ ]:
# NumPy Intersection & Difference
import numpy as np
n1 = np.array([10, 20, 30, 40, 50, 60])
n2 = np.array([50, 60, 70, 80, 90])
np.intersect1d(n1,n2)

array([50, 60])

In [ ]:
# NumPy Intersection & Difference
import numpy as np
n1 = np.array([10, 20, 30, 40, 50, 60])
n2 = np.array([50, 60, 70, 80, 90])
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [ ]:
# NumPy Intersection & Difference
import numpy as np
n1 = np.array([10, 20, 30, 40, 50, 60])
n2 = np.array([50, 60, 70, 80, 90])
np.setdiff1d(n2,n1)

array([70, 80, 90])

In [ ]:
# NumPy Array Mathematics
# Addition of NumPy Arrays
import numpy as np
n1=np.array([10, 20])
n2=np.array([30, 40])
np.sum([n1, n2])

100

In [ ]:
# NumPy Array Mathematics
# Addition of NumPy Arrays
import numpy as np
n1=np.array([10, 20])
n2=np.array([30, 40])
np.sum([n1, n2], axis=0)

array([40, 60])

In [ ]:
# NumPy Array Mathematics
# Addition of NumPy Arrays
import numpy as np
n1=np.array([10, 20])
n2=np.array([30, 40])
np.sum([n1, n2], axis=1)

array([30, 70])

In [ ]:
# NumPy Array Mathematics
# Basic Addition
import numpy as np
n1=np.array([10, 20, 30])
n1=n1+1
n1

array([11, 21, 31])

In [ ]:
# NumPy Array Mathematics
# Basic Multiplication
import numpy as np
n1=np.array([10, 20, 30])
n1=n1*2
n1

array([20, 40, 60])

In [ ]:
# NumPy Array Mathematics
# Basic Subtraction
import numpy as np
n1=np.array([10, 20, 30])
n1=n1-1
n1

array([ 9, 19, 29])

In [ ]:
# NumPy Array Mathematics
# Basic Division
import numpy as np
n1=np.array([10, 20, 30])
n1=n1/2
n1

array([ 5., 10., 15.])

In [ ]:
# NumPy Math Functions
# Mean
import numpy as np
n1=np.array([10, 20, 30, 40, 50, 60])
np.mean(n1)

35.0

In [ ]:
# NumPy Math Functions
# Median
import numpy as np
n1=np.array([11, 44, 5, 96, 67, 85])
np.median(n1)

55.5

In [ ]:
# NumPy Math Functions
# Standard Deviation
import numpy as np
n1=np.array([1, 5, 3, 100, 4, 48])
np.std(n1)

36.59424666377065

In [ ]:
# NumPy Save & Load
# Saving Numpy Array
import numpy as np
n1 = np.array([10, 20, 30, 40, 50, 60])
np.save('my_numpy', n1)

In [ ]:
# NumPy Save & Load
# Load Numpy Array
n2 = np.load('my_numpy.npy')
n2

array([10, 20, 30, 40, 50, 60])

In [1]:
# Python Pandas
# Pandas stands for Panel Data and core library for data manipulation and data analysis
# It consists of single and multi-dimensional data structures for data manipulations
# Single-dimensional is known as Series Object Multi-dimensional is known as Data Frame

# Series Object is one-dimensional labeled array
import pandas as pd
s1=pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [2]:
type(s1)

pandas.core.series.Series

In [6]:
# Passing a list
import pandas as pd
s1=pd.Series([11,12,13,14,15])
s1

0    11
1    12
2    13
3    14
4    15
dtype: int64

In [7]:
# Passing a list with index attribute
import pandas as pd
s1=pd.Series([1,2,3,4,5], index = ['a', 'b', 'c', 'd', 'e'])
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [8]:
# Passing a dictionary here
import pandas as pd
s1=pd.Series({'a':10, 'b':20, 'c':30})
s1

a    10
b    20
c    30
dtype: int64

In [9]:
# Passing a dictionary here
import pandas as pd
s1=pd.Series({'a':10, 'b':20, 'c':30}, index = ['a', 'b', 'c', 'd'])
s1

a    10.0
b    20.0
c    30.0
d     NaN
dtype: float64

In [10]:
# Passing a dictionary here
import pandas as pd
s1=pd.Series({'a':10, 'b':20, 'c':30}, index = ['b', 'c', 'd', 'a'])
s1

b    20.0
c    30.0
d     NaN
a    10.0
dtype: float64

In [11]:
# Extracting Individual Elements
# Extracting a single element
import pandas as pd
s1=pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9])
s1[3]

4

In [15]:
# Extracting Elements from back
import pandas as pd
s1=pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9])
s1[-3:]

6    7
7    8
8    9
dtype: int64

In [16]:
# Extracting a sequence of Elements
import pandas as pd
s1=pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9])
s1[:4]

0    1
1    2
2    3
3    4
dtype: int64

In [17]:
# Basic Math Operations on Series
# Adding a scalar value to Series Elements
import pandas as pd
s1=pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9])
s1+10

0    11
1    12
2    13
3    14
4    15
5    16
6    17
7    18
8    19
dtype: int64

In [24]:
# Basic Math Operations on Series
# Subtracting a scalar value to Series Elements
import pandas as pd
s1=pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9])
s1-10

0   -9
1   -8
2   -7
3   -6
4   -5
5   -4
6   -3
7   -2
8   -1
dtype: int64

In [25]:
# Basic Math Operations on Series
# Multiplying a scalar value to Series Elements
import pandas as pd
s1=pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9])
s1*10

0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
8    90
dtype: int64

In [22]:
# Adding two Series Objects
import pandas as pd
s1 = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9])
s2 = pd.Series([10, 20, 30, 40, 50, 60, 70, 80, 90])
s1+s2

0    11
1    22
2    33
3    44
4    55
5    66
6    77
7    88
8    99
dtype: int64

In [26]:
#@title Default title text
# Introduction to Pandas Dataframe
# Dataframe is a 2-dimensional labelled data-structure
# A data-frame comprises of rows and columns
# This is how you can create a data frame
import pandas as pd
pd.DataFrame({"Name":["Bob", 'Sam', 'Anne'], "Marks":[76,25,92]})

Name  Marks
0   Bob     76
1   Sam     25
2  Anne     92

In [42]:
import pandas as pd
iris = pd.read_csv('/content/sample_data/mnist_test.csv')
iris.head()

7  0  0.1  0.2  0.3  0.4  ...  0.662  0.663  0.664  0.665  0.666  0.667
0  2  0    0    0    0    0  ...      0      0      0      0      0      0
1  1  0    0    0    0    0  ...      0      0      0      0      0      0
2  0  0    0    0    0    0  ...      0      0      0      0      0      0
3  4  0    0    0    0    0  ...      0      0      0      0      0      0
4  1  0    0    0    0    0  ...      0      0      0      0      0      0

[5 rows x 785 columns]

In [43]:
iris.tail()

7  0  0.1  0.2  0.3  0.4  ...  0.662  0.663  0.664  0.665  0.666  0.667
9994  2  0    0    0    0    0  ...      0      0      0      0      0      0
9995  3  0    0    0    0    0  ...      0      0      0      0      0      0
9996  4  0    0    0    0    0  ...      0      0      0      0      0      0
9997  5  0    0    0    0    0  ...      0      0      0      0      0      0
9998  6  0    0    0    0    0  ...      0      0      0      0      0      0

[5 rows x 785 columns]

In [44]:
iris.shape

(9999, 785)

In [46]:
iris.describe()

7       0     0.1     0.2  ...   0.664   0.665   0.666   0.667
count  9999.000000  9999.0  9999.0  9999.0  ...  9999.0  9999.0  9999.0  9999.0
mean      4.443144     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
std       2.895897     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
min       0.000000     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
25%       2.000000     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
50%       4.000000     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
75%       7.000000     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
max       9.000000     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0

[8 rows x 785 columns]

In [48]:
# Extracting First 3 Rows and 2 Columns from the Dataframe
iris.iloc[0:3, 0:2]

7  0
0  2  0
1  1  0
2  0  0

In [56]:
# More Pandas Functions
# Mean
iris.mean()

7        4.443144
0        0.000000
0.1      0.000000
0.2      0.000000
0.3      0.000000
           ...   
0.663    0.000000
0.664    0.000000
0.665    0.000000
0.666    0.000000
0.667    0.000000
Length: 785, dtype: float64

In [57]:
# Median
iris.median()

7        4.0
0        0.0
0.1      0.0
0.2      0.0
0.3      0.0
        ... 
0.663    0.0
0.664    0.0
0.665    0.0
0.666    0.0
0.667    0.0
Length: 785, dtype: float64

In [58]:
# Minimum
iris.min()

7        0
0        0
0.1      0
0.2      0
0.3      0
        ..
0.663    0
0.664    0
0.665    0
0.666    0
0.667    0
Length: 785, dtype: int64

In [59]:
# Maximum
iris.max()

7        9
0        0
0.1      0
0.2      0
0.3      0
        ..
0.663    0
0.664    0
0.665    0
0.666    0
0.667    0
Length: 785, dtype: int64